### ISSUE TITLE
Drop six 1.9 support

### ISSUE THREAD

**Issue by gsnedders** [html5lib/html5lib-python#370] opened 2017-11-28 22:35 UTC
The version of `pytest` on Travis's 3.6 environment seems to rely on `six>=1.10` so our `six==1.9` test config fails. See, e.g., https://travis-ci.org/html5lib/html5lib-python/jobs/308631931

Given 1.10 is now over two years old, I'd hope we can drop support for 1.9, and fix this by just bumping our min required version to 1.10.

**Comment by gsnedders** [comment] 2017-11-28 22:36
(see #301, #298 for the 1.9 requirement)

**Comment by willkg** [comment] 2017-11-28 22:48
I wonder if this isn't related to Travis, but rather that we don't specify which version of pytest to install and use:

https://github.com/html5lib/html5lib-python/blob/master/requirements-test.txt#L4

I forget if that file affects what gets installed, but can look into it in a couple of hours or tomorrow.

**Comment by hugovk** [comment] 2020-02-26 14:36
Whatever the cause, this is no longer happening, the 3.6 env is passing on Travis (and all of them: 2.7, 3.5-3.8, PyPy and PyPy3).

Latest master build:

* https://travis-ci.org/html5lib/html5lib-python/builds/655163448

Can this issue now be closed?

---

In case you do want to bump to six 1.10, here's a passing branch I can PR:

* https://travis-ci.org/hugovk/html5lib-python/builds/655374557

(And https://github.com/html5lib/html5lib-python/pull/429 and https://github.com/html5lib/html5lib-python/pull/441 will bump to latest pytest 5.)

**Comment by ambv** [comment] 2023-03-01 18:46
Currently html5lib works with six 1.9+, including the latest 1.16.0 (example: https://ci.appveyor.com/project/gsnedders/html5lib-python/builds/46378000/job/kfed1o7y9uw02q9i). We can close this.

**Closed by ambv** 2023-03-01 18:46 UTC
