### ISSUE TITLE
do you have a plan time to drop the ugly version number like 0.999999999?

### ISSUE THREAD

**Issue by zaazbb** [html5lib/html5lib-python#348] opened 2017-09-16 15:28 UTC
do you have a plan time to drop the ugly version number  like 0.999999999?

**Comment by ikirudennis** [comment] 2017-09-17 14:27
Seriously. It's been over a year since 1.0b10/0.999999999 was released. Isn't it time to pull the trigger?

**Comment by drafter250** [comment] 2017-09-21 13:14
Hi thanks for your work on this project!

I was reviewing my package listing due to the following article, https://www.bleepingcomputer.com/news/security/ten-malicious-libraries-found-on-pypi-python-package-index/

While thankfully i did not find any of the packages in that list I noticed the odd version number for html5lib and it triggered me to investigate the package further to make sure it was legit. I would respectfully suggest a bump to a new version to avoid drawing negative attention to your project. Thanks!

**Comment by anx-ckreuzberger** [comment] 2017-10-03 10:51
I would also like to emphasis the importance of releasing "1.0" and start using [semantic versioning](http://semver.org/).

**Comment by willkg** [comment] 2017-10-03 14:00
This is a duplicate of #282. I'm closing it out.

**Closed by willkg** 2017-10-03 14:00 UTC
